=== gtec-medical-engineering/gpype/examples/paradigms/ParadigmSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:msdata="urn:schemas-microsoft-com:xml-msdata"
           targetNamespace="xsd"
           xmlns:xsi="xsd"
           elementFormDefault="qualified">


	<!-- TYPE DEFINITIONS -->

  <!-- Stimuli -->

	<xs:complexType name="Stimulus" abstract="true">
    <xs:attribute name="UdpMessage" type="xs:string"/>
    <xs:attribute name="LslMessage" type="xs:string"/>
  </xs:complexType>

	<xs:complexType name="VisualStimulus" abstract="true">
		<xs:complexContent>
			<xs:extension base="xsi:Stimulus">
				<xs:attribute name="HorizontalAlignment"    type="xsi:HorizontalAlignment"   default="Center"/>
				<xs:attribute name="VerticalAlignment"      type="xsi:VerticalAlignment"     default="Center"/>
				<xs:attribute name="Scaling"                type="xsi:Scaling"               default="Manual"/>
				<xs:attribute name="ManualScalingPercent"   type="xsi:NonNegativeDouble"     default="100"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="StaticVisualStimulus" abstract="true">
		<xs:complexContent>
			<xs:extension base="xsi:VisualStimulus">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="PictureStimulus">
		<xs:complexContent>
			<xs:extension base="xsi:StaticVisualStimulus">
				<xs:attribute name="FileName" type="xs:string"  use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="TextStimulus">
		<xs:complexContent>
			<xs:extension base="xsi:StaticVisualStimulus">
				<xs:attribute name="Caption"     type="xs:string"     default=""/>
				<xs:attribute name="Color"       type="xsi:HexRGB"    default="FFFFFF"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="AudioStimulus">
		<xs:complexContent>
			<xs:extension base="xsi:Stimulus">
				<xs:attribute name="FileName"      type="xs:string"                   use="required"/>
				<xs:attribute name="VolumePercent" type="xsi:Max100NonNegativeDouble" default="100"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="VideoStimulus">
		<xs:complexContent>
			<xs:extension base="xsi:VisualStimulus">
				<xs:attribute name="VolumePercent" type="xsi:Max100NonNegativeDouble" default="100"/>
				<xs:attribute name="FileName"      type="xs:string"                   use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Port">
		<xs:attribute name="Index"       type="xsi:DigitalOutPortIndex"  use="required"/>
		<xs:attribute name="FrequencyHz" type="xsi:NonNegativeDouble"    default="0"/>
	</xs:complexType>

	<xs:complexType name="DigitalOutStimulus">
		<xs:complexContent>
			<xs:extension base="xsi:Stimulus">
				<xs:choice minOccurs="1" maxOccurs="16">
					<xs:element name="Port" type="xsi:Port"/>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


  <!-- Contexts -->
  <xs:complexType name="Contexts">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="Context" type="xsi:Context"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Context">
    <xs:attribute name="ID" type="xs:NCName" use="required"/>
    <xs:attribute name="TargetGroup" type="xs:string" use="required"/>
    <xs:attribute name="DelaySeconds" type="xs:double" use="required"/>
    <xs:attribute name="DurationSeconds" type="xsi:NonNegativeDouble" use="required"/>
  </xs:complexType>

	<!-- Tasks -->
	<xs:complexType name="Node" abstract="true">
		<xs:attribute name="Label"   type="xs:string"   default=""/>
	</xs:complexType>

	<xs:complexType name="GenericTask" abstract="true">
		<xs:complexContent>
			<xs:extension base="xsi:Node">
				<xs:attribute name="Multiplicity" type="xs:positiveInteger"  default="1"/>
				<xs:attribute name="ID"           type="xs:NCName"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- SingleTask -->
	<xs:complexType name="SingleTask" mixed="true">
		<xs:complexContent>
			<xs:extension base="xsi:GenericTask">
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
          <xs:element name="Stimulus" type="xsi:Stimulus" minOccurs="0">
            <xs:unique name="UniquePortKey">
              <xs:selector xpath="xsi:Port" />
              <xs:field xpath="@Index" />
            </xs:unique>
          </xs:element>
        </xs:sequence>
				<xs:attribute name="Group"           type="xs:nonNegativeInteger" default="0"/>
				<xs:attribute name="DurationSeconds"                              default="1">
					<xs:simpleType>
						<xs:restriction base="xs:double">
							<xs:minInclusive value="0.01"/>
							<xs:maxInclusive value="1200"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<!-- MultiTask -->
	<xs:complexType name="MultiTask" mixed="true">
		<xs:complexContent>
			<xs:extension base="xsi:GenericTask">
				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="Task" type="xsi:GenericTask"/>
				</xs:choice>
				<xs:attribute name="TaskOrder"    type="xsi:TaskOrder"         default="Deterministic"/>
				<xs:attribute name="SampleSize"   type="xs:nonNegativeInteger" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<!-- Paradigm -->
	<xs:complexType name="Paradigm" mixed="true">
		<xs:complexContent>
			<xs:extension base="xsi:Node">
				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="Task" type="xsi:GenericTask"/>
				</xs:choice>
				<xs:attribute name="TaskOrder"             type="xsi:TaskOrder"         default="Deterministic" />
				<xs:attribute name="SampleSize"            type="xs:nonNegativeInteger" default="0"/>
				<xs:attribute name="BaseFolder"            type="xs:string"             default="./"/>
				<xs:attribute name="BackgroundColor"       type="xsi:HexRGB"            default="000000"/>
				<xs:attribute name="UdpAddress"            type="xs:string"             use="optional"/>
        <xs:attribute name="UdpPort"               type="xs:nonNegativeInteger" use="optional"/>
        <xs:attribute name="LslStreamName"         type="xs:string"             use="optional"/>
      </xs:extension>
		</xs:complexContent>
	</xs:complexType>





	<!-- Additional Groups/Types -->

	<xs:simpleType name="HexRGB">
		<xs:restriction base="xs:hexBinary">
			<xs:length value="3"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="HorizontalAlignment">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Left"/>
			<xs:enumeration value="Center"/>
			<xs:enumeration value="Right"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="VerticalAlignment">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Top"/>
			<xs:enumeration value="Center"/>
			<xs:enumeration value="Bottom"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Scaling">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Fit"/>
			<xs:enumeration value="Fill"/>
			<xs:enumeration value="Stretch"/>
			<xs:enumeration value="Manual"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="NonNegativeDouble">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Max100NonNegativeDouble">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="DigitalOutPortIndex">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="15"/>
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="TaskOrder">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Deterministic"/>
			<xs:enumeration value="RandomWithReplacement"/>
			<xs:enumeration value="RandomWithoutReplacement"/>
		</xs:restriction>
	</xs:simpleType>

  

	<xs:complexType name="XmlData" mixed="true">
    <xs:all>
      <xs:element name="Paradigm"   type="xsi:Paradigm"   minOccurs="1"/>
      <xs:element name="Contexts"    type="xsi:Contexts"  minOccurs="0" />
    </xs:all>
  </xs:complexType>



	<!-- ELEMENT DEFINITION -->

	<xs:element name="Data" type="xsi:XmlData">

	</xs:element>


</xs:schema>

=== gtec-medical-engineering/gpype/examples/paradigms/AEPOddball.xml
<?xml version="1.0" encoding="utf-8"?>
<Data xmlns="xsd" xmlns:ns="http://www.w3.org/2001/XMLSchema-instance" ns:schemaLocation="xsd ParadigmSchema.xsd">
  <Paradigm BaseFolder="media/" TaskOrder="Deterministic" UdpAddress="127.0.0.1" UdpPort="1000">
    <Task ns:type="SingleTask" ID="ST_PreParadigm" DurationSeconds="20" Group="0">
      <Stimulus ns:type="PictureStimulus" FileName="Checkerboard_Rest.png" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" />
    </Task>
      <Task ns:type="MultiTask" SampleSize="480">
        <Task ns:type="MultiTask" TaskOrder="RandomWithoutReplacement" SampleSize="1">
          <Task ns:type="SingleTask" ID="Target" DurationSeconds="0.25" Group="1">
            <Stimulus ns:type="AudioStimulus" FileName="Target.wav" UdpMessage="1"/>
          </Task>
          <Task ns:type="SingleTask" ID="Non_Target" DurationSeconds="0.25" Group="2" Multiplicity="7">
            <Stimulus ns:type="AudioStimulus" FileName="Nontarget.wav" UdpMessage="2"/>
          </Task>
        </Task>
        <Task ns:type="MultiTask" TaskOrder="RandomWithReplacement" SampleSize="1">
          <Task ns:type="SingleTask" DurationSeconds="0.2" Group="0"/>
          <Task ns:type="SingleTask" DurationSeconds="0.3" Group="0"/>
          <Task ns:type="SingleTask" DurationSeconds="0.4" Group="0"/>
        </Task>
      </Task>
    <Task ns:type="SingleTask" DurationSeconds="10">
      <Stimulus ns:type="TextStimulus" Caption="Thank You!" />
    </Task>
  </Paradigm>
</Data>

=== gtec-medical-engineering/gpype/examples/paradigms/AEPSingleStim.xml
<?xml version="1.0" encoding="utf-8"?>
<Data  xmlns="xsd" xmlns:ns="http://www.w3.org/2001/XMLSchema-instance" ns:schemaLocation="xsd ../ParadigmSchema.xsd">
  <Paradigm BaseFolder="media/" TaskOrder="Deterministic" UdpAddress="127.0.0.1" UdpPort="1000">
    <Task ns:type="SingleTask" ID="ST_PreParadigm" DurationSeconds="20" Group="0">
      <Stimulus ns:type="PictureStimulus" FileName="Checkerboard_Rest.png" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" />
    </Task>
	<Task ns:type="MultiTask" ID="MT_Wrapper" TaskOrder="Deterministic" SampleSize="100">
	
	
		<!-- COPY ME IN HERE -->
		<Task ns:type="MultiTask" ID="MT_Stim" TaskOrder="RandomWithoutReplacement" SampleSize="1">
		 <Task ns:type="SingleTask" ID="Beep_50ms_1000Hz" DurationSeconds="0.20" Group="1">
		  <Stimulus ns:type="AudioStimulus" FileName="Beep_50ms_1000Hz.wav" UdpMessage="1"/>
		 </Task>
		</Task>
		
		
		<Task ns:type="MultiTask" ID="MT_Rest" TaskOrder="RandomWithReplacement" SampleSize="1">
			<Task ns:type="SingleTask" ID="ST_Rest1" DurationSeconds="1.00" Group="0">
			  <Stimulus ns:type="TextStimulus" Caption="" />
			</Task>
			<Task ns:type="SingleTask" ID="ST_Rest2" DurationSeconds="1.25" Group="0">
			  <Stimulus ns:type="TextStimulus" Caption="" />
			</Task>
			<Task ns:type="SingleTask" ID="ST_Rest3" DurationSeconds="1.50" Group="0">
			  <Stimulus ns:type="TextStimulus" Caption="" />
			</Task>
			<Task ns:type="SingleTask" ID="ST_Rest4" DurationSeconds="1.75" Group="0">
			  <Stimulus ns:type="TextStimulus" Caption="" />
			</Task>
		</Task>
	</Task>
  </Paradigm>
</Data>

=== gtec-medical-engineering/gpype/examples/paradigms/HandPose/HandPose_Left.xml
<?xml version="1.0" encoding="utf-8"?>
<Data xmlns="xsd" xmlns:ns="http://www.w3.org/2001/XMLSchema-instance" ns:schemaLocation="xsd ..\ParadigmSchema.xsd">

  <Paradigm BaseFolder="media_left/" TaskOrder="Deterministic" UdpAddress="127.0.0.1" UdpPort="1000">
    <Task ns:type="SingleTask" ID="ST_PreParadigm" DurationSeconds="10">
      <Stimulus ns:type="TextStimulus" Caption="+" />
    </Task>
    <Task ns:type="MultiTask" ID="MT_TaskSequence" TaskOrder="Deterministic" SampleSize="120">
      <Task ns:type="MultiTask" ID="MT_Move" TaskOrder="RandomWithoutReplacement" SampleSize="1">
        <Task ns:type="SingleTask" ID="ST_Fist" DurationSeconds="1" Group="1">
          <Stimulus ns:type="PictureStimulus" FileName="fist.jpg" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Manual" ManualScalingPercent="100" UdpMessage="1"/>/>
        </Task>
        <Task ns:type="SingleTask" ID="ST_Hand" DurationSeconds="1" Group="2">
          <Stimulus ns:type="PictureStimulus" FileName="hand.jpg" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Manual" ManualScalingPercent="100" UdpMessage="2"/>/>
        </Task>
        <Task ns:type="SingleTask" ID="ST_Peace" DurationSeconds="1" Group="3">
          <Stimulus ns:type="PictureStimulus" FileName="peace.jpg" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Manual" ManualScalingPercent="100" UdpMessage="3"/>/>
        </Task>
      </Task>
      <Task ns:type="MultiTask" ID="MT_Distract" TaskOrder="RandomWithReplacement" SampleSize="1">
        <Task ns:type="SingleTask" ID="ST_Distractor1" DurationSeconds="1.5" Group="99">
          <Stimulus ns:type="PictureStimulus" FileName="fist_scrambled.jpg" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Manual" ManualScalingPercent="100" UdpMessage="99"/>
        </Task>
        <Task ns:type="SingleTask" ID="ST_Distractor2" DurationSeconds="2.0" Group="99">
          <Stimulus ns:type="PictureStimulus" FileName="hand_scrambled.jpg" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Manual" ManualScalingPercent="100" UdpMessage="99"/>
        </Task>
        <Task ns:type="SingleTask" ID="ST_Distractor3" DurationSeconds="2.5" Group="99">
          <Stimulus ns:type="PictureStimulus" FileName="peace_scrambled.jpg" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Manual" ManualScalingPercent="100" UdpMessage="99"/>
        </Task>
      </Task>
    </Task>
    <Task ns:type="SingleTask" ID="ST_PostParadigm" DurationSeconds="5">
      <Stimulus ns:type="TextStimulus" Caption="Thank You!" />
    </Task>
  </Paradigm>
</Data>

=== gtec-medical-engineering/gpype/examples/paradigms/CheckerboardFace.xml
<?xml version="1.0" encoding="utf-8"?>
<Data  xmlns="xsd" xmlns:ns="http://www.w3.org/2001/XMLSchema-instance" ns:schemaLocation="xsd ../ParadigmSchema.xsd">

  <Paradigm BaseFolder="media/" TaskOrder="Deterministic" UdpAddress="127.0.0.1" UdpPort="1000">
    <Task ns:type="SingleTask" ID="ST_PreParadigm" DurationSeconds="20" Group="0">
      <Stimulus ns:type="PictureStimulus" FileName="Checkerboard_Rest.png" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" />
    </Task>
	<Task ns:type="MultiTask" ID="MT_Wrapper" TaskOrder="Deterministic" SampleSize="300">
	
		<Task ns:type="MultiTask" ID="MT_Stim" TaskOrder="RandomWithoutReplacement" SampleSize="1">
		 <Task ns:type="SingleTask" ID="Checkerboard_05" DurationSeconds="0.15" Group="1" Multiplicity="20">
		  <Stimulus ns:type="PictureStimulus" FileName="Checkerboard_05.png" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" UdpMessage="1"/>
		 </Task>
		 <Task ns:type="SingleTask" ID="Checkerboard_41" DurationSeconds="0.15" Group="2" Multiplicity="20">
		  <Stimulus ns:type="PictureStimulus" FileName="Checkerboard_41.png" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" UdpMessage="2"/>
		 </Task>
		 <Task ns:type="MultiTask" ID="MT_Face" TaskOrder="RandomWithReplacement" SampleSize="1" Multiplicity="10">
			<Task ns:type="SingleTask" ID="Face01" DurationSeconds="0.15" Group="3">
				<Stimulus ns:type="PictureStimulus" FileName="f01.jpg" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" UdpMessage="3"/>
			</Task>
			<Task ns:type="SingleTask" ID="Face02" DurationSeconds="0.15" Group="3">
				<Stimulus ns:type="PictureStimulus" FileName="f02.jpg" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" UdpMessage="3"/>
			</Task>
			<Task ns:type="SingleTask" ID="Face03" DurationSeconds="0.15" Group="3">
				<Stimulus ns:type="PictureStimulus" FileName="f03.jpg" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" UdpMessage="3"/>
			</Task>
			<Task ns:type="SingleTask" ID="Face04" DurationSeconds="0.15" Group="3">
				<Stimulus ns:type="PictureStimulus" FileName="f04.jpg" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" UdpMessage="3"/>
			</Task>
			<Task ns:type="SingleTask" ID="Face06" DurationSeconds="0.15" Group="3">
				<Stimulus ns:type="PictureStimulus" FileName="f06.jpg" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" UdpMessage="3"/>
			</Task>
			<Task ns:type="SingleTask" ID="Face07" DurationSeconds="0.15" Group="3">
				<Stimulus ns:type="PictureStimulus" FileName="f07.jpg" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" UdpMessage="3"/>
			</Task>
		 </Task>
		</Task>
		
		
		<Task ns:type="MultiTask" ID="MT_Rest" TaskOrder="RandomWithReplacement" SampleSize="1">
			<Task ns:type="SingleTask" ID="ST_Rest1" DurationSeconds="0.6" Group="0">
			  <Stimulus ns:type="PictureStimulus" FileName="Checkerboard_Rest.png" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" />
			</Task>
			<Task ns:type="SingleTask" ID="ST_Rest2" DurationSeconds="0.7" Group="0">
			  <Stimulus ns:type="PictureStimulus" FileName="Checkerboard_Rest.png" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" />
			</Task>
			<Task ns:type="SingleTask" ID="ST_Rest3" DurationSeconds="0.8" Group="0">
			  <Stimulus ns:type="PictureStimulus" FileName="Checkerboard_Rest.png" HorizontalAlignment="Center" VerticalAlignment="Center" Scaling="Fit" />
			</Task>
		</Task>
	</Task>
  </Paradigm>
</Data>

=== gtec-medical-engineering/gpype/examples/paradigms/Checkerboard/Checkerboard.xml
<?xml version="1.0" encoding="utf-8"?>
<Data  xmlns="xsd"
           xmlns:ns="http://www.w3.org/2001/XMLSchema-instance"
           ns:schemaLocation="xsd ..\ParadigmSchema.xsd">

	<Paradigm BaseFolder="media/" TaskOrder="Deterministic" UdpAddress="127.0.0.1" UdpPort="1000">
		<Task ns:type="SingleTask" ID="ST_PreParadigm" DurationSeconds="10">
			<Stimulus ns:type="TextStimulus" Caption="+"/>
		</Task>
		<Task ns:type="MultiTask" ID="MT_Checkerboard" TaskOrder="Deterministic" SampleSize="60">
			<Task ns:type="SingleTask" ID="ST_Checkerboard1" DurationSeconds="0.7" Group="1">
				<Stimulus ns:type="PictureStimulus" FileName="chk1.png" UdpMessage="1"/>
			</Task>
			<Task ns:type="SingleTask" ID="ST_Checkerboard2" DurationSeconds="0.7" Group="2">
				<Stimulus ns:type="PictureStimulus" FileName="chk2.png" UdpMessage="2"/>
			</Task>
		</Task>
		<Task ns:type="SingleTask" ID="ST_PostParadigm" DurationSeconds="2">
			<Stimulus ns:type="TextStimulus" Caption="Thank You!"/>
		</Task>
	</Paradigm>
</Data>
